name: Run Mobilewright

on:
  push:
    branches: ["*"]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build .ipa for iOS real device
        run: |
          make ipa

      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v5
        with:
          name: ipa-build
          path: build/Milliways-unsigned.ipa

  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      MOBILE_USE_API_KEY: ${{ secrets.MOBILE_USE_API_KEY }}
    steps:
      - uses: actions/checkout@v5

      - name: Download .ipa artifact
        uses: actions/download-artifact@v5
        with:
          name: ipa-build
          path: build

      - name: Run tests using mobilewright
        working-directory: tests
        run: |
          # some of the tests are expected to fail, so we're adding || true
          npm ci --ignore-scripts
          npm run test || true

      - name: Upload test report
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: mobilewright-report
          path: tests/mobilewright-report

      - uses: aws-actions/configure-aws-credentials@v5
        if: always()
        with:
          role-to-assume: ${{ secrets.AWS_SAMPLES_UPLOAD_ROLE_ARN }}
          aws-region: us-west-2

      - name: Upload samples to S3
        if: always()
        run: |
          GITSHA=$( git rev-parse HEAD )
          aws s3 cp --quiet --recursive --acl public-read tests/mobilewright-report s3://mobilewright-samples/milliways/runs/$GITSHA
          echo "→ Report uploaded to https://mobilewright-samples.s3.amazonaws.com/milliways/runs/$GITSHA/index.html"
          echo "### 📊 Test Report" >> $GITHUB_STEP_SUMMARY
          echo "[View Mobilewright Report](https://mobilewright-samples.s3.amazonaws.com/milliways/runs/$GITSHA/index.html)" >> $GITHUB_STEP_SUMMARY
